### ISSUE TITLE
Oak example doesnt Compile

### ISSUE THREAD

**Issue by StraightUpCode** [denjucks/session#3]
Hello! 
I was trying to test this librarie for a class project, but I wasn't able to get past the example code for the Oak Framework with a compile error: 
Code:
```typescript
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import { Session } from "https://deno.land/x/session/mod.ts";

const app = new Application();

// Configuring Session for the Oak framework
const session = new Session({ framework: "oak" });
await session.init();

// Adding the Session middleware. Now every context will include a property
// called session that you can use the get and set functions on
app.use(session.use()(session));


// Creating a Router and using the session
const router = new Router();

router.get("/", async (context) => {

    // Examples of getting and setting variables on a session
    if (await context.session.get("pageCount") === undefined) {
        await context.session.set("pageCount", 0);

    } else {
        await context.session.set("pageCount", await context.session.get("pageCount") + 1);
    }
    
    context.response.body = `Visited page ${await context.session.get("pageCount")} times`;
});

app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 8000 });
```

```sh
deno run --allow-net mod.ts
Compile file:///home/rsanchez/projectos/session/mod.ts
error: TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string | undefined>, Record<string, any>>'.
    if (await context.session.get("pageCount") === undefined) {
                      ~~~~~~~
    at file:///home/rsanchez/projectos/session/mod.ts:21:23

TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string | undefined>, Record<string, any>>'.
        await context.session.set("pageCount", 0);
                      ~~~~~~~
    at file:///home/rsanchez/projectos/session/mod.ts:22:23

TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string | undefined>, Record<string, any>>'.
        await context.session.set("pageCount", await context.session.get("pageCount") + 1);
                      ~~~~~~~
    at file:///home/rsanchez/projectos/session/mod.ts:25:23

TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string | undefined>, Record<string, any>>'.
        await context.session.set("pageCount", await context.session.get("pageCount") + 1);
                                                             ~~~~~~~
    at file:///home/rsanchez/projectos/session/mod.ts:25:62

TS2339 [ERROR]: Property 'session' does not exist on type 'RouterContext<Record<string | number, string | undefined>, Record<string, any>>'.
    context.response.body = `Visited page ${await context.session.get("pageCount")} times`;
                                                          ~~~~~~~
    at file:///home/rsanchez/projectos/session/mod.ts:28:59

```

**Comment by denjucks** [comment]
Change the file extension to .js and run. In the library I add a session object to the context, which is allowable in JS, but will be caught by the TS compiler since the context by default doesn't have this property available. You can still use TS elsewhere in the project, for example in controllers, but have an app.js file to set configurations for the application and to create routes that interact with a controller. Hopefully this help!

**Comment by denjucks** [comment]
Added support for TS in v1.1.0. See new example in the readme
